# Site Settings
title: "Ipek Selcen - Progress Blog"
description: "Tracking my journey in chromatin biology and bioinformatics"
url: "https://ipekselcen.github.io"
baseurl: ""

# Build Settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md 
