
title: Ipek Selcen — Molecular Biology & Bioinformatics
description: Portfolio, projects, and writing on epigenetics, cloning, molecular biology, and my journey into bioinformatics.
theme: minima
author:
  name: Ipek Selcen
  email: your.email@example.com
url: ""  # set this to https://<your-username>.github.io once deployed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
show_excerpts: true
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/<your-username>" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/<your-handle>/" }
    - { platform: orcid, user_url: "https://orcid.org/<your-orcid>" }
collections:
  projects:
    output: true
    permalink: /projects/:name/
nav_pages:
  - index.md
  - about.md
  - projects.md
  - publications.md
  - blog.md
  - cv.md
  - contact.md
