title: Ipek Selcen - Molecular Biology & Bioinformatics
email: ipek.selcen@gmail.com
description: >-
  Portfolio showcasing bioinformatics projects, epigenetics work, and scientific editorial samples.
url: "https://ipekselcen.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: "default"

# Optional defaults so all pages render correctly
defaults:
  - scope: { path: "" }
    values:
      layout: single
      author_profile: false  # turn on per page where you want the sidebar
