title: Ipek Selcen - Molecular Biology & Bioinformatics
description: Portfolio, projects, and writing on epigenetics, molecular biology, and my journey into bioinformatics.

author: Ipek Selcen
email: ipek.selcen@gmail.com

url: "https://ipekselcen.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "air"   # or: default, mint, contrast, dark, etc.

markdown: kramdown
kramdown:
  input: GFM

show_excerpts: true

minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/ipekselcen" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ipek-selcen-16516948/" }
    - { platform: orcid,   user_url: "https://orcid.org/0000-0001-7614-1780" }

# This creates the top header menu
header_pages:
  - about.md
  - projects.md
  - publications.md
  - blog.md
  - cv.md
  - contact.md
