title: Ipek Selcen — Molecular Biology & Bioinformatics
email: ipek.selcen@gmail.com
description: >-
  Portfolio showcasing bioinformatics projects, epigenetics work, and scientific editorial samples.
url: "https://ipekselcen.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: "default"

defaults:
  - scope: { path: "" }
    values:
      layout: single
      author_profile: false

collections:
  projects:
    output: true
    permalink: /projects/:name/
  editorial:
    output: true
    permalink: /editorial/:name/

